-- create database business;
-- create table SalesmanTable(
-- Salesman_id int not null primary key,
-- Name varchar(20) not null,
-- City varchar(20) not null,
-- Commission float not null
-- );
-- insert into salesmantable values(5001,'James Hoog','New York',0.15);
-- insert into salesmantable values(5002,'Nail Knite','Paris',0.13);
-- insert into salesmantable values(5005,'Pit Alex','London',0.11);
-- insert into salesmantable values(5006,'Mc Lyon','Paris',0.14);
-- insert into salesmantable values(5007,'Paul Adam','Rome',0.13);
-- insert into salesmantable values(5003,'Lauson Hen','San Jose',0.12);
-- create table CustomerTable(
-- Customer_id int not null primary key,
-- Cust_Name varchar(30) not null,
-- City varchar(20) not null,
-- Grade int not null,
-- Salesman_id int not null
-- );
-- insert into Customertable values(3002,'Nick Rimnado','New York',100,5001);
-- insert into Customertable values(3007,'Brad Davis','New York',200,5001);
-- insert into Customertable values(3005,'Graham Zusi','California',200,5002);
-- insert into Customertable values(3008,'Jaulin Green','London',300,5002);
-- insert into Customertable values(3004,'Fabin Johnson','Paris',300,5006);
-- insert into Customertable values(3009,'Geoff Cameron','Berlin',100,5003);
-- insert into Customertable values(3003,'Jozy Altidor','Moscow',200,5007);
-- insert into Customertable values(3001,'Brad Guzan','London',0,5005);
-- Query 1
-- select Name,Cust_Name from SalesmanTable,CustomerTable where salesmanTable.City=CustomerTable.City;
-- Query 2
-- Statement isn't given properly in the Assignment.
-- Query 3

